version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symfony/console
    versions:
    - 5.2.1
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/expression-language
    versions:
    - 5.2.1
    - 5.2.3
  - dependency-name: symfony/asset
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/browser-kit
    versions:
    - 5.2.1
    - 5.2.3
  - dependency-name: symfony/dotenv
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/property-info
    versions:
    - 5.2.1
    - 5.2.3
  - dependency-name: symfony/web-profiler-bundle
    versions:
    - 5.1.10
  - dependency-name: symfony/framework-bundle
    versions:
    - 5.1.10
